### ISSUE TITLE
Research Values

### ISSUE THREAD

**Issue by luney-sp-76** [SetGoals/Goals#2]
- What values are there?
- A List of human values.
- What are values?

Are there groupings of values / are they more individual

**Goal**
3-5 overarching values to base personal traits on

**Comment by mysticrecords** [comment]
**Theory of Basic Human Values**
*https://en.wikipedia.org/wiki/Theory_of_Basic_Human_Values*

- when thinking of a common values map linking traits to values are the 4 higher order groups something to consider

**Personal Values Assessment**
*https://www.valuescentre.com/tools-assessments/pva/*

- could be worth looking at to see how / what questions are asked to determine values important to people if they aren't sure what their values are?? *(when talking about suggesting values to users)*

**Top Ten Values Of Humanity**
*https://www.worldvaluesday.com/top-ten-values-humanity/*

- interesting article based on 500,000 survey responses showing top 10 values of these people and how these fit into seven levels of consciousness model

**Seven Levels of Consciousness Model**
*https://www.valuescentre.com/barrett-model/*

![image](https://user-images.githubusercontent.com/47884688/168912592-b80ba886-9451-4a68-bf30-0153ff15ca9a.jpeg)

**Comment by luney-sp-76** [comment]
A.H Maslow: Psychologist who founded theories on motivation  that became the basis for Barretts Model: 
http://psychclassics.yorku.ca/Maslow/motivation.htm

**Comment by luney-sp-76** [comment]
I found in the Barrett two versions of the same 7 pillars: 
The basic 3 main sections of  one  are **Foundation, Evolution and Purpose** the other **Self Interest, Transformation and Common Good**. The differences I think depend on the audience they are aiming at as they have personal and business models. The former 3 are business centric and the latter more personal in my view. What are your thoughts Matt?

Both are in the [Wiki](https://github.com/SetGoals/Goals/wiki/Barret-Values)

**Comment by luney-sp-76** [comment]
I also shared this with you already in text but just to keep it easy to find: [wordApi](https://www.wordsapi.com/#try)

The rational is the API can preload lots of similar words to the overarching Values. Giving the user options around what Values they like. This adds a sense of customizablity (sic) for the user who can then use terms they understand and relate to.

**Comment by mysticrecords** [comment]
> I found in the Barrett two versions of the same 7 pillars: The basic 3 main sections of one are **Foundation, Evolution and Purpose** the other **Self Interest, Transformation and Common Good**. The differences I think depend on the audience they are aiming at as they have personal and business models. The former 3 are business centric and the latter more personal in my view. What are your thoughts Matt?
> 
> Both are in the [Wiki](https://github.com/SetGoals/Goals/wiki/Barret-Values)

Yes, seen this Paul.  I feel initially the personal model and pillars would be worth limiting our scope to.  That's not to say we couldn't design it in a way that, in later iterations we could explore the business model also.  

The mind map you've put together is extensive as well, thank you for putting this together.  It would be great to sit down together and discuss our way through this.

**Comment by mysticrecords** [comment]
After our meeting on the 30/05/22 having agreed on the initial scope of the project, we are going to limit this to goals and habits.

I will close this issue for now.  Interesting topic thought and could be something that could be introduced in future iterations.
