### ISSUE TITLE
Research Personal Traits

### ISSUE THREAD

**Issue by luney-sp-76** [SetGoals/Goals#3]
**Research and create a list of Positive Personal Traits**<br>
Personal Traits will link to one or more Values 
A list of traits are needed to mind map the traits and values together

**Comment by luney-sp-76** [comment]
Personal traits positive
* 
* 		Being honest and taking responsibility for your actions are admirable qualities.
* 		Adaptability and affability are great traits that can help a person get along well with others.
* 		Drive, determination and persistence can help keep a person going no matter what.
* 		Compassion, understanding and empathy help a person relate well to others.
* 		In addition to being a virtue, patience is a personality trait that's universally valued.
* 		Courage and confidence can help a person choose to do what is right in tough situations.
* 		Loyalty is a good quality to possess; it will help others decide that you are trustworthy.
* 		Being adventurous and fearless can empower you to be willing to take chances.
* 		Having an imaginative and creative nature can help you come up with innovative ideas and unique solutions.
* 		Being helpful to others is a personality trait that will cause others to see you as indispensable.
* 		Being meticulous and precise means that you're careful and conscientious.
* 		A person who is optimistic tends to look for the bright side of situations rather than forcing on the negative.
* 		Someone who is reliable and dependable is an individual that others know they can count on.
* 		People who are gregarious, charming or sociable tend to be friendly, outgoing and upbeat.
* 		Those who are independent develop a reputation for taking initiative and seeing things through on their own. 
* 		People who are fair and impartial are viewed by others as being able to make objective decisions not influenced by bias.
* 		Those who take an encouraging approach are viewed as being caring and interested in seeing others succeed.
* 		People who are humble tend to be viewed as those who can succeed without being arrogant about their accomplishments.
* 		If people view you as capable and competent, they tend to trust that you know what you are doing.
* 		Those who are exuberant come across as being filled with joy and enthusiasm.
* 		People who are discreet are viewed as trustworthy individuals who are respectful of the privacy and dignity of others.


Personality traits negative

* 		A propensity for lying in order to avoid responsibility for one's actions is a deplorable quality.
* 		A tendency to be untruthful or dishonest in your dealings with others is also a negative trait.
* 		Being rigid and consistently unyielding to the needs of others are not endearing qualities.
* 		Being full of laziness and excuses for failing to meet obligations is sure to drive others away.
* 		An inability to empathize with others is a negative personality trait that can alienate others.
* 		Being quick to anger will damage relationships and turn people away.
* 		Being disloyal, such as talking about others behind their backs or betraying them for personal gain, is among the most negative personality traits.
* 		People who are bossy tend to come across as self-centered individuals who disregard the concerns of others.
* 		Those who are conceited, pompous or arrogant tend to think that they have all the answers or universally know better than everyone else.
* 		Those who are unfriendly are often viewed as disrespectful and/or uninterested in connecting with other people.
* 		People who are sullen or surly by nature can be very rude and unpleasant to deal with in a personal or professional capacity.
* 		Those who are cowardly exhibit an unwillingness to face adversity head-on or to stand up for what is right.
* 		People who tend to be slovenly habitually fail to take care of their appearance or surroundings, and so are viewed negatively by others.
* 		People who are quarrelsome or argumentative by nature are more concerned with winning arguments and being right than with finding a solution.
* 		Those who are too finicky or picky come across as extreme perfectionists who cannot be pleased no matter what one does.
* 		People who tend to be impulsive often act without thinking about the consequences to themselves or others, thus coming across as reckless.
* 		Those who are habitually stingy or greedy are viewed by others as selfish individuals who disregard the needs of others.
* 		People who are sneaky tend to be deliberately deceptive, factors that most definitely represent negative personality traits.
* 		Those who engage in malicious acts deliberately do things that they know will negatively impact other people.
* 		Those who are thoughtless act with a total disregard for how their actions might impact other people.
* 		Those who behave in an unruly manner are often disruptive and disrespectful and can cause harm to others by their irresponsible actions.

**Comment by mysticrecords** [comment]
**Personality Traits**

*source of list of traits above*

https://examples.yourdictionary.com/examples-of-personality-traits.html

**Comment by mysticrecords** [comment]
Similar to research value issue, having limited scope to focus on goals and habits I will close this issue for now.
